This is makeindex, version 2.15 [MiKTeX 2.9.6210 64-bit] (kpathsea + Thai support).
Scanning style file ./finalReportComputeTemplate.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file finalReportComputeTemplate.acn....done (31 entries accepted, 0 rejected).
Sorting entries....done (178 comparisons).
Generating output file finalReportComputeTemplate.acr....done (65 lines written, 0 warnings).
Output written in finalReportComputeTemplate.acr.
Transcript written in finalReportComputeTemplate.alg.
