This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./finalReportComputeTemplate.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file finalReportComputeTemplate.acn....done (67 entries accepted, 0 rejected).
Sorting entries....done (432 comparisons).
Generating output file finalReportComputeTemplate.acr....done (75 lines written, 0 warnings).
Output written in finalReportComputeTemplate.acr.
Transcript written in finalReportComputeTemplate.alg.
